config/routes.rb
EMagAPP::Application.routes.draw do


  get "sign_in" => 'sessions#new', :as => :sign_in


  post "sessions/create"

  get "sessions/destroy" => 'sessions#destroy', :as => :sign_out

  root to: 'emags#index'
  resources :emags
  resources :users
  resources :comments
  resources :orders
  resources :favorites
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password
  
  validates_length_of :password, :minimum=>6

  has_secure_password

  validates_uniqueness_of :name
  validates_presence_of :name
  has_many :emags
  has_many :comments
  def num
  	@number=Emag.where(:user_id => self.id).count
  	return @number
  	
  end
  def author
    @author=Order.where(:user_id => self.id).author
    return @author
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
     
    before_filter :authorize_user,  :except => [:index, :new, :create]
   
  def authorize_user
    @user = User.find(params[:id])
    if @user.id != session[:user_id]
      redirect_to root_url, notice: "Try again"
    end
  end

   def index
   	   @users=User.all


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
   	
   end

   def show
   	  @user=User.find(params[:id])


   	respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
   	
   end
   def new
    @user=User.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end

     
   end
   def edit
    @user=User.find(params[:id])

     
   end
   def create
    @user=User.new(params[:user])
    respond_to do |format|
      if @user.save
        session["user_id"] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
     
   end
   def update
    @user=User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
     
   end

   def destroy
      @user=User.find(params[:id])
      @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
     
   end


end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
    	<h2><%= pluralize(@user.errors.count, "error") %>
    		prohibited this user from being saved:</h2>

    		<ul>
    			<% @user.errors.full_messages.each do |msg| %>
    			  <li><%= msg %></li>
    			 <% end %>
    		</ul>
    </div>
    			  
   <% end %>

  <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
  </div>
  <div class="field">
     <%= f.label :password %><br>
     <%= f.password_field :password %>
  </div>
  <div class="actions">
  	 <%= f.submit %>
  </div>
  <% end %>	 

app/views/users/edit.html.erb
<h1> Edit User</h1>
<%= render 'form' %>
<%= link_to 'Show', @user %>
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<h2>Profile for <%= @user.name %></h2>
<h2>Artical Published: <%= @user.num %></h2>


<h2>Published Details :</h2>
<br>
<table>
	<thead>
		<tr>
			<th> Title </th>
		    <th>Content</th>
			<th>Description</th>
		</tr>
	</thead>
	<tbody>
	   <% @user.emags.each do |e| %>
		    <tr>
			    <td width=100 height=100 align=center><%= e.title %></td>
			    <td width=100 height=100 align=center><img src=<%= e.content %> height=100/></td>
			    <td width=100 height=100 align=center><%= e.description %></td>
			    <td width=100 height=100 align=center><%= link_to 'Edit', edit_emag_path(e) %></td>
			    <td width=100 height=100 align=center><%= link_to 'Destroy', e, method: :delete, data: {confirm: 'Are you sure?' } %></td>
			</tr> 
	   <% end %>
    </tbody>
</table>

<%= link_to 'Create a new Emag',new_emag_url %>
<%= link_to 'Edit', edit_user_path(@user) %>
<%= link_to 'Back', users_path %>
<h2>Emags You Have Ordered :</h2>
<br></br>
<table>
	<thead>
		<tr>
           <th> Author </th>
           <th> Title  </th>
           <th> Description </th>
           <th> Content </th>
		</tr>
	</thead>
	<tbody>
        
        <% @orders=Order.where(:user_id => session[:user_id]) %>

        <% @orders.each do |a| %>
        <% @emags=Emag.where(:author => a.author) %>

        <% @emags.each do |e| %>
        <tr>
           <td width=100 height=100 align=center><%= e.author %></td>
           <td width=100 height=100 align=center><%= e.title %></td>
           <td width=100 height=100 align=center><%= e.description %></td>
           <td width=100 height=100 align=center><img src=<%= e.content %> height=100/></td>
           <td width=100 height=100 align=center><%= link_to 'DisOrder', a, method: :delete, data: {confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
        <% end %>
	</tbody>
</table>
<h2>Emags in Your Favorites List :</h2>
<br></br>
<table>
	<thead>
		<tr>
           <th> Author </th>
           <th> Title  </th>
           <th> Description </th>
           <th> Content </th>
		</tr>
	</thead>
	<tbody>
        
        <% @favorites=Favorite.where(:user_id => session[:user_id]) %>

        <% @favorites.each do |a| %>
        <% @emags=Emag.where(:title => a.title) %>

        <% @emags.each do |e| %>
        <tr>
           <td width=100 height=100 align=center><%= e.author %></td>
           <td width=100 height=100 align=center><%= e.title %></td>
           <td width=100 height=100 align=center><%= e.description %></td>
           <td width=100 height=100 align=center><img src=<%= e.content %> height=100/></td>
           <td width=100 height=100 align=center><%= link_to 'DisFavorite', a, method: :delete, data: {confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
        <% end %>
	</tbody>
</table>