config/routes.rb
EMagAPP::Application.routes.draw do


  get "sign_in" => 'sessions#new', :as => :sign_in


  post "sessions/create"

  get "sessions/destroy" => 'sessions#destroy', :as => :sign_out

  root to: 'emags#index'
  resources :emags
  resources :users
  resources :comments
  resources :orders
  resources :favorites
end

app/models/emag.rb
class Emag < ActiveRecord::Base
  attr_accessible :author, :description, :content, :title, :user_id
  belongs_to :user
  has_many :comments
  def comment
  	@comment=Comment.where(:emag_id => self.emag_id)
  	return @comment
  	
  end
end

app/controllers/emags_controller.rb
class EmagsController < ApplicationController
	def index
	
        @emags=Emag.order("title asc").limit(30)
        if params[:search].present?
           k=params[:search]
           @emags=@emags.where("title LIKE ?","%#{k}%")
        end

        @emags = @emags.page(params[:page]).per(10)

	end
	def edit
		@emag=Emag.find(params[:id])

	end

	def update
		@emag=Emag.find(params[:id])
    respond_to do |format|
      if @emag.update_attributes(params[:emag])
        format.html { redirect_to @emag, notice: 'Emag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @emag.errors, status: :unprocessable_entity }
      end
    end
	end
	def new
		@emag=Emag.new
		@emag.user_id=session[:user_id]
		respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @emag }
        end
		
	end
	def create
       @emag = Emag.new(params[:emag])
       @emag.user_id=session[:user_id]
    respond_to do |format|
      if @emag.save
        format.html { redirect_to @emag, notice: 'Emag was successfully created.' }
        format.json { render json: @emag, status: :created, location: @emag }
      else
        format.html { render action: "new" }
        format.json { render json: @emag.errors, status: :unprocessable_entity }
      end
     end
    end
    def show
    	@emag=Emag.find(params[:id])

       respond_to do |format|
       format.html # show.html.erb
       format.json { render json: @emag }
       end	
    end
   def destroy
   	 @emag=Emag.find(params[:id])
     @emag.destroy
     respond_to do |format|
      format.html { redirect_to emags_url }
      format.json { head :no_content }
    end
   	
   end
		
	


end	

app/views/emags/_form.html.erb
<%= form_for(@emag) do |f| %>
  <% if @emag.errors.any? %>
     <div id="error_explanation">
     	<h2><%= pluralize(@emag.errors.count, "error") %> prohibited this emag from being saved: </h2>
        <ul>
        <%= @emag.errors.full_message.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
     </div>
  <% end %>
  <div class="field">
  	 <%= f.label :title %><br>
  	 <%= f.text_field :title %>
  </div>
  <div class="field">
     <%= f.label :author %><br>
     <%= f.text_field :author %>
  </div>
  <div class="field">
      <%= f.label :content %><br>
      <%= f.text_field :content %>
  </div>
  <div class="field">
      <%= f.label :description %><br>
      <%= f.text_field :description %>
  </div>
  <div class="actions">
      <%= f.submit %>
  </div>
<% end %>  	 

app/views/emags/edit.html.erb
<h1> Edit Your Emag</h1>
<%= render 'form' %>
<%= link_to 'Show', @emag %>
<%= link_to 'Back', emags_path %>

app/views/emags/index.html.erb
<div class="row">
	<div class="span12">
		<h1 class="page-header" >Welcome to Emags</h1>
		<%= paginate @emags %>
		<table class="table table-hover">
			<thead>
				<tr>
					<th>Author</th>
					<th> Title</th>
					<th>Content</th>
					<th>Description</th>
				</tr>
			</thead>
			<tbody>
			   <% @emags.each do |e| %>
			   <tr>
			     <td width=100 height=100 align=center><%= e.author %></td>
			     <td width=100 height=100 align=center><%= e.title %></td>
			     <td width=200 height=200 align=center><img src=<%= e.content %> width=200 height=200/></td>
			     <td width=100 height=100 align=center><%= e.description %></td>
			      <% if session[:user_id] %>
                     <td><%= link_to 'Show', emag_url(e) %> </td>
                  <% else %>
                     <td>Sign Up!</td>
                  <% end %>
			   </tr> 
			   <% end %>
           </tbody>
        </table>
    </div>
</div>

app/views/emags/new.html.erb
<h1>New Emag</h1>

<%= render 'form' %>
<%= link_to 'Back', emags_path %>

app/views/emags/show.html.erb
<p id="notice"><%= notice %></p>
<p>
	<b>Title :</b>
	<%= @emag.title %>
</p>
<p>
  <b>Author :</b>
  <%= @emag.author %>
</p>

<p>
    <b>Content :</b>

    <img src="<%= @emag.content %>" width=50 height=50>
</p>

<p>
    <b>Description :</b>
    <%= @emag.description %>
</p>
<table>
  <thead>	
	<tr>
		<th>Comment</th>
		<th>Commented By</th>
	</tr>
  </thead>
  <tbody>
  	<% @comments=Comment.where(:emag_id => @emag.id) %>
  	<% @comments.each do |c| %>
  	<% @commenter=User.find(c.user_id) %>
  	<tr>
       <th width=600 height=100 align=center><%= c.comment %></th>
        <th width=200 height=100 align=center><%= @commenter.name%></th>
        <th width=200 height=100 align=center><%= link_to 'Destroy', c, method: :delete, data: {confirm: 'Are you sure?' } %></th>
  	</tr>
    <% end %>
  </tbody>


</table>


<%= link_to 'Edit', edit_emag_path(@emag) %>
<%= link_to 'Back', emags_path %>
<%= link_to 'Comment',{:controller =>'comments', :action => 'new', :id => @emag.id }  %>

<%= link_to 'Make an Order', {:controller =>'orders', :action => 'new', :author => @emag.author}  %>
<%= link_to 'Make it as a Favorite', {:controller =>'favorites', :action => 'new', :title => @emag.title}  %>