config/routes.rb
EMagAPP::Application.routes.draw do


  get "sign_in" => 'sessions#new', :as => :sign_in


  post "sessions/create"

  get "sessions/destroy" => 'sessions#destroy', :as => :sign_out

  root to: 'emags#index'
  resources :emags
  resources :users
  resources :comments
  resources :orders
  resources :favorites
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EMagAPP</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body >
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand span2" href="/">Emags</a>
        <div class="nav-collapse">
          <form class="navbar-search pull-left" action="">
            <input type="text" class="search-query span3" placeholder="Search by title of Emags" name="search">
          </form>
          <ul class="nav pull-right">
            <% if session[:user_id] %>
              <li><%= link_to "My Profile", user_url(session[:user_id]) %></li>
              <li><%= link_to "Sign Out", sign_out_url %></li>
            <% else %>
              <li><%= link_to "Sign Me Up!", new_user_url %></li>
              <li><%= link_to "Sign In", sign_in_url %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>
<%= yield %>


</body>

</html>